
'''
snakemake --profile slurm --use-conda
sinteractive -p interactive --time=1-00:00:00 --cpus-per-task=1
'''

LAMS = [0.5]
LIST_OF_NONLIN_FACTORS = ['none','20'] #, cannot put commas in widlcard bug in snakemake, e.x '0-1-2'
STR_AB_EXP = ['fetal_erythropoesis_new']
SEEDS = [0, 1, 2, 3]
rule all:
    input:
        expand('Out_files_and_results/{str_ab_exp}/seed={seed}_lambda={lam}_list_of_nonlin_factors={list_of_nonlin_factors}/done.txt',
               lam=LAMS,
               list_of_nonlin_factors=LIST_OF_NONLIN_FACTORS,
               str_ab_exp=STR_AB_EXP,
                seed = SEEDS
               )
       # 'intermediate_results/spectra_results_fetal_liver_erythroid_with_50H.npy'

rule run_palava:
    output:
        'Out_files_and_results/{str_ab_exp}/seed={seed}_lambda={lam}_list_of_nonlin_factors={list_of_nonlin_factors}/done.txt'
    resources:
        runtime=600,
        mem_mb=100000,#150000
        cpus=1,
        gres='gpu:1',
        account='punim0614',
        partition= 'gpu-a100,mig-gpu', 
        output_dr= lambda wildcards: f"Out_files_and_results/{wildcards.str_ab_exp}/seed={wildcards.seed}_lambda={wildcards.lam}_list_of_nonlin_factors={wildcards.list_of_nonlin_factors}/run_palava_%x.%j.out",
        job_name= 'scvi_palava'
    conda:
        "palava-env"
    shell:
        """
        python scVI_palava_erythropoesis_data.py --lambda_='{wildcards.lam}' --str_ab_exp='{wildcards.str_ab_exp}' --list_of_nonlin_factors='{wildcards.list_of_nonlin_factors}' --seed='{wildcards.seed}' --dir='seed={wildcards.seed}_lambda={wildcards.lam}_list_of_nonlin_factors={wildcards.list_of_nonlin_factors}'
        """


rule run_spectra:
    input:
       "data/{adata}.h5ad"
    output: 
        'intermediate_results/spectra_results_{adata}.npy'
    resources:
        runtime= 5000,
        mem_mb= 100000,
        cpus= 1,
        gres = 'gpu:0',
        account = 'punim0614',
        partition = 'cascade,mig',
        output_dr = 'Out_files/run_spectra_%x.%j.out',
        job_name = 'real_data_spectra'
    conda:
       "spectra-fresh-env"
    params:
       data_dr = "data/{adata}.h5ad"

    shell:
        """
        conda list
        pip list
        python run_spectra.py --data_directory='{params.data_dr}'
        """


